### ISSUE TITLE
Connection timed out

### ISSUE THREAD

**Issue by hwgeone** [wenfh2020/kernel_test#2]
大佬，根据文档一步步都做完了，最后Vs code debug的时候，出现如下error

Unable to start debugging. Unexpected GDB output from command "-target-select remote 127.0.0.1:1234". 127.0.0.1:1234: Connection timed out.

请问这个问题如何解决，linux下1234端口是在哪里设置的？

**Comment by hwgeone** [comment]
已解决

**Comment by wenfh2020** [comment]
> 已解决

good，根据视频，不要漏掉步骤哈。。
